### ISSUE TITLE
Search results are hard to read 

### ISSUE THREAD

**Issue by teemue** [mudlej/mj_pdf#10]
Reading search results is hard in dark mode - text colors are not optimal. Screenshot attached.![Screenshot_20230701-120135.jpg](https://github.com/mudlej/mj_pdf/assets/317905/d732b788-808a-494e-bfc8-2b1ba3852ceb)

**Comment by mudlej** [comment]
Solved in V2.1.
Coming soon.

**Comment by mudlej** [comment]
Fixed in [!7](https://gitlab.com/mudlej_android/mj_pdf_reader/-/merge_requests/7).
