### ISSUE TITLE
I cant find it on Google Play

### ISSUE THREAD

**Issue by inson1** [mudlej/mj_pdf#11]

**Comment by mudlej** [comment]
Google has changed their policy and I must update the app to comply with the new one.
Will do it soon.

**Comment by mudlej** [comment]
It's available right now.
https://play.google.com/store/apps/details?id=com.gitlab.mudlej.MjPdfReader

**Comment by inson1** [comment]
sorry for spam, I'm just reorganizing my solved issues - jg8tzJHCu0Qcc1zJGcht

**Comment by bonjour81** [comment]
Hi, Seems to be gone again ?
