### ISSUE TITLE
opening recent apps with MJ PDF makes the phone slow down

### ISSUE THREAD

**Issue by ChuckBartowski91** [mudlej/mj_pdf#12]
Hello, If I open MJ PDF and I then open recent apps while I'm into them the phone slows down, at the point that its hard to scroll through the opened apps. No issue with the app or when it's in background and I'm using another one.

My phone is xiaomi 11 lite 5g ne with android 13 (miui 14.0.6 vf)

**Comment by mudlej** [comment]
I am aware of the issue. 
I don't know why, but it's because of the monochrome icon I added in v2.1.0.

I fixed the problem in v2.1.1 which will be available within 48 hours.
