### ISSUE TITLE
cannot open app info into settings (it closes itself)

### ISSUE THREAD

**Issue by ChuckBartowski91** [mudlej/mj_pdf#13]
Hello, If I try to open the MJ PDF info into settings it crashes and trying multiple times shows the message: the security app keeps interrupting.

My phone is xiaomi 11 lite 5g ne with android 13 (miui 14.0.6 vf)

**Comment by mudlej** [comment]
Fixed in: https://gitlab.com/mudlej_android/mj_pdf_reader/-/merge_requests/8
