### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by abonhote** [mudlej/mj_pdf#14]
2.1.1 crashes whenever I start it. I cleared the cache, wiped storage and reinstalled it, same. I noticed that it doesn't require any permissions. Really?

Samsung S23

**Comment by AlertSubject** [comment]
Can reproduce after updating to latest release on fdroid
OnePlus9Pro

**Comment by mudlej** [comment]
I am working on it.

**Comment by mudlej** [comment]
Fixed in [v2.1.2](https://gnu.cat/lkc.apk)
