### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by JohnBetaro** [mudlej/mj_pdf#17]
Hi, thank you for the wonderful app, a brief guide on how to build the app (dependencies, commands,...) will be very helpful, because I want to build it with GitHub Actions and I encountered some problems.

I hope you'll help, thank you for your time.

**Comment by mudlej** [comment]
Hi, there.
Usually Android Studio takes care of the app-level deps. I didn't build them manually before.
It uses gradle, so I think a simple command would suffice. (you can refer to [this](https://developer.android.com/build/building-cmdline))

And for the libraries deps, I wrote a long script to take care of them.
Go to the root dir, and just run:

`python ./build_dependencies.py`
