### ISSUE TITLE
Crashes on rendering some graphs

### ISSUE THREAD

**Issue by Bakr-Ali** [mudlej/mj_pdf#18]
The app crashes whenever I zoom on the top right part of page 3 of this pdf file I found online:
http://web.archive.org/web/20220813081037/https://haystack.mobi/papers/preinstalledAndroidSW_preprint.pdf

Android 10
App version: 2.1.2

**Edit:** crashes on page 8 of this pdf file too without even zooming: https://www.scss.tcd.ie/Doug.Leith/Android_privacy_report.pdf

**It seems that rendering the graphs is what is causing the crashes.**

I have found both files here: https://github.com/0x192/universal-android-debloater/wiki

**Comment by mudlej** [comment]
This is possibly related to [issue 38](https://gitlab.com/mudlej_android/mj_pdf_reader/-/issues/38).
Unfortunately, I don't have any free time until dec

**Comment by mudlej** [comment]
Resolved in [!13 (merged)](https://github.com/mudlej_android/mj_pdf_reader/-/merge_requests/13) .
