### ISSUE TITLE
[Feature request] Document autoreload or reload button

### ISSUE THREAD

**Issue by Dioprz** [mudlej/mj_pdf#20]
Hello!

First, thank you very much for developing MJ PDF. It has been a pleasure to use the application. The interface, options and performance have been outstanding so far.

That being said, I wanted to ask if you would be interested in developing an automatic or manual document refresh option, such as the one you request here: https://www.reddit.com/r/fossdroid/comments/yv9bkz/comment/j12mjyk/?utm_source=share&utm_medium=web2x&context=3

I frequently edit documents and would like to see their compilation reflected as it happens. Currently, however, it seems that the document is cached and does not reload on changes.

Although the application does not have this option, I have managed to simulate the "reload" behavior when changing the document theme, so one option might be that such a button would do theme change twice and that would suffice.

In any case, I'm already saving a lot of clicks in my workflow as before the only option I had was to close and reopen the document, so.... Thanks for that.

Good luck!

**Comment by mudlej** [comment]
This should be resolved [here](https://gitlab.com/mudlej_android/mj_pdf_reader/-/commit/9b5ee7c972e592ec001ce6dc4571a0510453105a).

Can you test verify it? [MJ PDF v2.2.0-beta](https://gnu.cat/eig.apk)

**Comment by mudlej** [comment]
Added [here](https://gitlab.com/mudlej_android/mj_pdf_reader/-/merge_requests/14/diffs?commit_id=386f441ed4a181bd051eb806013940d469b40485).
Should be included in v2.2.0

**Comment by Dioprz** [comment]
Thank you very much for all your work. Mj continues to be my default pdf reader, and it has been an excellent tool.

**Comment by mudlej** [comment]
You're welcome!

Btw, can you verify it's working?
Here is the new beta version [mj-pdf-2.2.0-beta.apk](https://gnu.cat/hxf)

**Comment by Dioprz** [comment]
Done! It works perfectly! I just noticed that the new feature is not shown in the startup popup with new features and fixes. If this is intentional, no problem; just wanted to let you know.

**Comment by mudlej** [comment]
Good to hear.
And yes, I didn't update that yet.
