### ISSUE TITLE
Request: host .apk directly

### ISSUE THREAD

**Issue by foolishgrunt** [mudlej/mj_pdf#23]
I'm trying to avoid using both Google Play Store (for privacy reasons) and F-Droid/IzzyOnDroid (for security reasons). The method I'm currently using for keeping my apps up-to-date is Obtanium, which can be configured a number of ways but typically downloads .apk's from the developers source repository (GitHub, GitLab, etc).

I note that you do not host .apk's directly on either of these sites, and instead link to pages on Archive.org. I can use Obtanium to download from there, but if the relevant URL changes with every release, there is no way for it to notify me when a new version has been released, which defeats the purpose.

With that in mind, I'd like to request that you consider hosting the .apk's directly on the GitLab page to make life easier for those of us using Obtanium (or similar projects). But I'm also curious, what advantage does hosting on Archive.org offer you as a developer?

**Comment by thekyber** [comment]
I am getting the app from APKPure, it is good so far, until we see what he will do about this situation.

https://apkpure.com/mj-pdf-fast-pdf-viewer/com.gitlab.mudlej.MjPdfReader

**Comment by mudlej** [comment]
It's hosted directly on Gitlab releases page [now](https://gitlab.com/mudlej_android/mj_pdf_reader/-/releases/V2.2.1).

Although, the URL won't be the same for every new version.

**Comment by foolishgrunt** [comment]
Thank you!

The URL for the .apks doesn't need to be identical across releases for Obtainium to work - it works on the same principles as an RSS feeder, so it will watch the Gitlab releases page and scrape it for few versions.
