### ISSUE TITLE
Display PDF names correctly from an SMB share

### ISSUE THREAD

**Issue by 0verEngineer** [mudlej/mj_pdf#24]
The pdf names are displayed with url encoding if i open it from an SMB share.

**Comment by mudlej** [comment]
Can you give instructions to reproduce this?

**Comment by 0verEngineer** [comment]
1. Connect to an SMB share in Material Files
2. Open a PDF from that SMB share
3. Read the name of the PDF

**Comment by mudlej** [comment]
I couldn't set up an SMB server on Linux and I don't have a Windows machine.
Can you at least provide a screenshot of the title?

**Comment by 0verEngineer** [comment]
![Screenshot_20240508-131446_MJ PDF_20240508131630.png](https://github.com/mudlej/mj_pdf/assets/105462605/6019aa04-2563-422c-9a31-fee6a25e5ca1)


You could use a docker image like dperson/samba for a smb server

**Comment by mudlej** [comment]
Can you try [this version](https://gnu.cat/dgj)?

**Comment by mudlej** [comment]
Prefect.
Will be included in v2.2.0
