### ISSUE TITLE
BUG when I scroll to the page 11 of this document

### ISSUE THREAD

**Issue by fredericoacardi** [mudlej/mj_pdf#27]
Hello. When I get to page 11 or 12 the app closes... Tried on the directlink download and with the latest from Izziondroid repo. Thank you. I am using Android 13 crdroid 9.9. With a Xioami redmi Note 12. 

It does not do it with mupdf, firefox, koreader or Librera. The file works fine. Good luck.
[AN_AMD_Prefetch_Attacks_Through_Power_and_Time.pdf](https://github.com/mudlej/mj_pdf/files/14838080/AN_AMD_Prefetch_Attacks_Through_Power_and_Time.pdf)

**Comment by mudlej** [comment]
Fixed in [!13](https://gitlab.com/mudlej_android/mj_pdf_reader/-/merge_requests/13) 
Will be included in v2.2.0
