### ISSUE TITLE
Bug: when no document loaded and tapping Full Screen

### ISSUE THREAD

**Issue by derei** [mudlej/mj_pdf#28]
I noticed an issue with the app: if opened without any document, and tapping Full Screen button, there is no way to turn it off. All on-screen controls disappear.

Suggested fix: make the full screen button only available if there is a document loaded.

**Comment by mudlej** [comment]
Fixed in this [commit](https://gitlab.com/mudlej_android/mj_pdf_reader/-/commit/9dde7cf593961d9f7a066d922e54d5385071cdaf). Will be included in v2.2.0
