### ISSUE TITLE
It doesn't exit on back button

### ISSUE THREAD

**Issue by lnxfsf** [mudlej/mj_pdf#29]
When I open pdf from file explorer it doesn't exit from this app on back button. 
it should exit the app

**Comment by mudlej** [comment]
Can you try this version [mj-pdf-v2.2.0-alpha.apk](https://gitlab.com/mudlej_android/mj_pdf_reader/uploads/02ed1cd14248e2528833ce16d39b100f/app-release.apk)

**Comment by lnxfsf** [comment]
yes, this one works

**Comment by lnxfsf** [comment]
in fact, it does close on back button, but when openong multiple document and exiting, then in "recent apps" I get all those multiple apps of this same app, i.e. all those opened and closed documents from explorer.


- And if I open some file by the mjpdf (explorer inside of it), then when i exit by back button, it exits. but when i enter mjpdf app again, it goes back to same pdf i was reading, instead of exiting that and just showing me it's inner explorer i.e. recents

**Comment by mudlej** [comment]
This is the expected behavior. Actually it's one of its [features](https://gitlab.com/mudlej_android/mj_pdf_reader#mj-pdf-features).

> Open multiple instance of the app at the same time.
