### ISSUE TITLE
Support for opening password protected PDFs

### ISSUE THREAD

**Issue by GET100PERCENT** [mudlej/mj_pdf#3]
It will be  very useful if this app can open password protected PDF files.

**Comment by mudlej** [comment]
MJ PDF already support it.
![password-file](https://user-images.githubusercontent.com/110748150/222524231-d8c7ad0c-530b-4287-8c53-40d88583af90.png)

**Comment by GET100PERCENT** [comment]
But when I try to open a password protected pdf it shows like this:
![Screenshot_20230303-004059](https://user-images.githubusercontent.com/116144024/222528113-48a326ad-0e83-4de1-8267-f1a6271b53e9.jpg)

**Comment by mudlej** [comment]
can you share a PDF file with this issue?

**Comment by GET100PERCENT** [comment]
Here is the pdf file:
[forum-f-droid-org-t-known-repositories-721 (1).pdf](https://github.com/mudlej/mj_pdf/files/10878011/forum-f-droid-org-t-known-repositories-721.1.pdf)

**Comment by GET100PERCENT** [comment]
> Here is the pdf file: [forum-f-droid-org-t-known-repositories-721 (1).pdf](https://github.com/mudlej/mj_pdf/files/10878011/forum-f-droid-org-t-known-repositories-721.1.pdf)

And the password is: 12345

**Comment by GET100PERCENT** [comment]
Not only in this file , all password protected pdfs show similar.

**Comment by mudlej** [comment]
That's strange. It opens normally for me.
![temp1](https://user-images.githubusercontent.com/110748150/222879054-7aa2f940-4ac3-4ccd-ba3f-3ec25dfd0e9d.png)
![temp2](https://user-images.githubusercontent.com/110748150/222879051-7edef9bf-ac4b-450b-a757-5e18a16ed4cc.png)

**Comment by mudlej** [comment]
Tested with several different devices, works on all of them.
Also, [!7](https://gitlab.com/mudlej_android/mj_pdf_reader/-/merge_requests/7) improved it by adding the ability to save the password, so you don't need to enter it every time.
