### ISSUE TITLE
Donations

### ISSUE THREAD

**Issue by pdtheowl** [mudlej/mj_pdf#5]
Hi, is there a way you accept financial donations?

**Comment by mudlej** [comment]
Hi,
Not yet.

**Comment by user8446** [comment]
Yes, you can now donate here: https://liberapay.com/mudlej/

**Comment by pdtheowl** [comment]
@mudlej can you verify this?

**Comment by user8446** [comment]
It's talked about here: https://www.reddit.com/r/fossdroid/comments/163x98a/mj_pdf_v21_is_out_with_material_you_theme/

However, I think the donation link should be on both github & gitlab so more in the community see it so people who don't have the ability to donate code can help development financially.

**Comment by pdtheowl** [comment]
Thank you, apologies for the doubt, just wanted to make sure since you're not one of the devs haha

Yes, it would be excellent if they had the link on the github page!

**Comment by pdtheowl** [comment]
@user8446 referred me to donation link with proof, closing
