### ISSUE TITLE
[Feature Request] lower contrast for dark mode

### ISSUE THREAD

**Issue by KernelDeimos** [mudlej/mj_pdf#6]
I'd like the text to be a little dimmer in dark mode. A transparent black overlay would be good enough for my purpose, but a contrast slider might be more generally helpful.

**Comment by mudlej** [comment]
Currently the dark mode just invert the colors.
The next version already has many new changes.
May be in MJ PDF v2.2 I can add such feature.

**Comment by mudlej** [comment]
Same as [#1](https://github.com/mudlej/mj_pdf/issues/1)
