### ISSUE TITLE
[Feature Request] ability to lock horizontal scroll when not in fullscreen

### ISSUE THREAD

**Issue by KernelDeimos** [mudlej/mj_pdf#7]
The horizontal scroll lock is really useful. I think it would be helpful if the horizontal scroll lock was always available rather than just when in fullscreen mode.

**Comment by mudlej** [comment]
The question is where to put it?
The only appropriate place I am thinking of the second bar. (shortcuts)
My intention was to make it customizable from the beginning, but I still didn't get the change to do that.

**Comment by mudlej** [comment]
Added [here](https://gitlab.com/mudlej_android/mj_pdf_reader/-/merge_requests/14/diffs?commit_id=b1c087f3a10b201082e466e09aefb0035d07339a). Will be included in v2.2.0
