### ISSUE TITLE
Be able to leave app on first back press

### ISSUE THREAD

**Issue by Junkyard-Dog-0101** [mudlej/mj_pdf#9]
I would like to be able to leave app on first back press and don't want to double click to leave app.

Maybe we could set this param in settings

![Screenshot_2023-06-23-11-57-37-72_441eb50f81cc1223b53314ede0235c21](https://github.com/mudlej/mj_pdf/assets/3962335/b0a55bd5-fe1f-4aa8-a456-e422f4596f8e)

**Comment by mudlej** [comment]
Done in [!7](https://gitlab.com/mudlej_android/mj_pdf_reader/-/merge_requests/7).
You can disable double tap to exist in the settings.
